obj-$(CONFIG_AM_WIFI_SD_MMC) +=  wifi_dt.o
obj-$(CONFIG_DHD_USE_STATIC_BUF) += dhd_static_buf.o
obj-$(CONFIG_AM_WIFI_USB) += wifi_power.o
obj-$(CONFIG_RTL8189ES) += realtek/rtl8189ES/
obj-$(CONFIG_RTL8723BS) += realtek/rtl8723BS/
obj-$(CONFIG_BCMDHD) += broadcom/bcmdhd_1_201_59_x/
